"""회원 채팅 표면. mdChat은 원격 런처의 공통 렌더러를 그대로 사용한다."""
from launcher_app_common import LAUNCHER_COMMON_JS


def member_html():
    return '''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>IndieBiz · 회원</title><style>
*{box-sizing:border-box}body{margin:0;background:#f6f5f1;color:#202a29;font:16px system-ui,sans-serif}main{max-width:840px;margin:0 auto;padding:32px 20px}header{display:flex;justify-content:space-between;align-items:center}h1{font-size:24px}small,#status{color:#62716d}#chat{min-height:45vh;margin:28px 0}.bubble{padding:18px 22px;border-radius:18px;margin:12px 0;white-space:pre-wrap;overflow-wrap:anywhere;background:white}.user{background:#e2eee7;margin-left:60px}.assistant{margin-right:40px}.bubble pre{overflow:auto;background:#f1f3f0;padding:12px}form{display:flex;gap:10px;position:sticky;bottom:0;background:#f6f5f1;padding:12px 0}textarea{flex:1;min-height:64px;border:1px solid #bdc9c1;border-radius:12px;padding:14px;font:inherit}button{background:#245644;color:white;border:0;border-radius:10px;padding:12px 18px;cursor:pointer}button.secondary{background:#e1e6e0;color:#203b31}button:disabled{opacity:.5}.approval{border:2px solid #b7832e;background:#fff8e9;border-radius:12px;padding:18px;margin:15px 0}.approval button{margin-right:8px}.approval pre{max-height:200px;overflow:auto;white-space:pre-wrap}details{margin-top:24px}#notice{font-size:14px;line-height:1.7}#approvals:empty{display:none}
</style><main><header><h1>내 기기와 함께</h1><button class="secondary" id="export">기억 내보내기</button></header>
<p id="notice">대화와 기억은 이 기기에 저장됩니다. 요청 내용은 허브와 모델 제공자를 거쳐 처리됩니다.</p><small id="status">연결 확인 중</small>
<section id="approvals" aria-live="polite"></section><section id="chat" aria-live="polite"></section>
<form id="send"><textarea id="message" placeholder="이 기기에서 할 일을 말해주세요" aria-label="메시지"></textarea><button id="sendButton">보내기</button><button type="button" class="secondary" id="cancel">중단</button></form>
<details><summary>최근 작업 결과</summary><div id="results"></div></details></main><script>window.__MEMBER=true;</script>''' + LAUNCHER_COMMON_JS + '''
const memberToken=location.hash.slice(1)||sessionStorage.getItem('member-token')||'';if(memberToken)sessionStorage.setItem('member-token',memberToken);history.replaceState(null,'',location.pathname);
const memberNativePending=new Map();let memberNativeId=0;
window.memberNativeResult=(id,value)=>{const resolve=memberNativePending.get(id);if(resolve){memberNativePending.delete(id);resolve(value)}};
async function memberRequest(path,body){if(window.MemberBridge){return new Promise(resolve=>{const id=String(++memberNativeId);memberNativePending.set(id,resolve);MemberBridge.request(id,path,JSON.stringify(body||{}))})}const r=await fetch('/member/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-Member-Token':memberToken},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error('연결 또는 인증을 확인해주세요');return r.json()}
function memberBubble(role,text){const d=document.createElement('div');d.className='bubble '+role;d.innerHTML=mdChat(text);document.getElementById('chat').append(d);d.scrollIntoView({block:'end'});}
let memberApprovalSignature='';
function memberApprovalText(c){const labels={op:'작업',action:'동작',path:'파일',dest:'옮길 곳',content:'내용',cmd:'명령',id:'프로그램',args:'입력',resources:'자원 파일',dependencies:'필요한 패키지',url:'주소',record:'저장할 기억'};const ops={write:'파일 저장',file_move:'파일 이동',mkdir:'폴더 만들기',script:'등록 프로그램',memory_save:'기억 저장',play:'재생',open:'열기',shell:'명령 실행'};return Object.entries(c).filter(([k])=>!['member','request_key','query_key'].includes(k)).map(([k,v])=>(labels[k]||k)+': '+(k==='op'?(ops[v]||v):typeof v==='string'?v:JSON.stringify(v,null,2))).join(String.fromCharCode(10))}
async function memberApprovals(){try{const items=await memberRequest('approvals');const signature=JSON.stringify(items);if(signature===memberApprovalSignature)return;memberApprovalSignature=signature;const box=document.getElementById('approvals');box.replaceChildren();for(const item of items){const d=document.createElement('div');d.className='approval';const label=document.createElement('b');label.textContent='이 기기에서 실행을 허용할까요?';const pre=document.createElement('pre');pre.textContent=memberApprovalText(item.command);d.append(label,pre);for(const [title,allow] of [['허용',true],['거절',false]]){const b=document.createElement('button');b.textContent=title;b.onclick=async()=>{await memberRequest('approve',{key:item.key,allow});await memberApprovals()};d.append(b)}box.append(d)}}catch(e){}}
async function memberBoot(){
try{const h=await memberRequest('history');for(const row of h.history||[])memberBubble(row.role,row.content)}catch(e){document.getElementById('status').textContent=e.message}
memberRequest('profile',{}).then(profile=>{document.getElementById('status').textContent=profile.success?'연결됨 · 오늘 '+profile.turns_today+'회 사용':'연결 확인 필요';if(profile.notice)document.getElementById('notice').textContent+=' '+profile.notice}).catch(()=>{document.getElementById('status').textContent='오프라인 · 기억과 결과는 이 기기에 보존됨'});
document.getElementById('send').onsubmit=async e=>{e.preventDefault();const field=document.getElementById('message'),message=field.value.trim();if(!message)return;field.value='';memberBubble('user',message);document.getElementById('sendButton').disabled=true;document.getElementById('status').textContent='작업 중 · 필요한 실행은 위에서 승인해주세요';try{const r=await memberRequest('chat',{message});memberBubble('assistant',r.response||r.error||'응답 없음');document.getElementById('status').textContent=r.memory_saved?'완료 · 이 기기에 기억 저장됨':'작업 종료 · 기억 저장 상태를 확인하세요'}catch(e){memberBubble('assistant',e.message)}finally{document.getElementById('sendButton').disabled=false;refreshMemberResults()}};
document.getElementById('cancel').onclick=()=>memberRequest('close',{});
document.getElementById('export').onclick=async()=>{const r=await memberRequest('export',{});memberBubble('assistant',r.success?'내보내기 완료: '+r.path:r.error)};
setInterval(memberApprovals,1000);setInterval(refreshMemberResults,5000);refreshMemberResults();}
async function refreshMemberResults(){try{const rows=await memberRequest('results');const d=document.getElementById('results');d.replaceChildren();for(const row of rows||[]){const p=document.createElement('p');p.textContent=(row.state==='unknown'?'결과 불명 — 자동 재실행하지 않았습니다':'완료')+' · '+row.key+' · '+JSON.stringify(row.command||row.result||{});d.append(p)}}catch(e){}}
</script></html>'''
