"""회원 작업 공간: 로컬 작업 목록·자율주행·공통 앱 프레임·파일 편집."""
import json
from member_app_frame import frame_html

WORKSPACE_STYLE = '''
[hidden]{display:none!important}main{max-width:1280px;padding:22px}header h1{margin:0}#workspaceLayout{display:grid;grid-template-columns:230px minmax(0,1fr);gap:28px;margin-top:24px}#workArea,#taskSidebar{min-width:0}#taskSidebar{border-right:1px solid #d4ded7;padding-right:20px}#taskList button{display:block;background:transparent;color:#355548;text-align:left;width:100%;margin:6px 0;padding:12px}#taskList button.active{background:#e2eee7}#workspacePath{display:block;overflow-wrap:anywhere;margin:14px 0;font-size:13px}#memberNav{display:flex;gap:8px;margin:18px 0}#memberNav button{background:#e2e8e2;color:#284f3e}#memberNav button.active{background:#245644;color:white}#appFrame{width:100%;height:70vh;border:0}#taskProgress{color:#5b7266;font-size:13px;max-height:180px;overflow:auto}#fileEditor{width:100%;min-height:300px;font:14px ui-monospace,monospace}#fileRows button{margin:5px;background:#e7eee8;color:#264b37}#filePath{width:70%;padding:12px;border:1px solid #b9c9c0;border-radius:8px}#workspacePicker{width:100%;padding:10px;box-sizing:border-box}#chat{min-height:35vh}#approvals{position:sticky;top:0;z-index:10}#taskTitle{font-size:22px}#taskQuestion{padding:16px;background:#fff5dc;border-radius:12px;white-space:pre-wrap}#taskControls{display:flex;gap:12px;align-items:center;margin:12px 0}#taskQuestion:empty{display:none}#taskProgress:empty{display:none}.taskState{font-size:12px;color:#617366}.fileActions{display:flex;gap:10px;margin:12px 0}@media(max-width:700px){#workspaceLayout{grid-template-columns:minmax(0,1fr)}#workArea,#taskSidebar{min-width:0}#taskSidebar{border-right:0;border-bottom:1px solid #d4ded7;padding-bottom:15px}#taskList{display:flex;overflow:auto}#taskList button{min-width:150px}header h1{font-size:20px}}
'''
SIDEBAR = '''<div id="workspaceLayout"><aside id="taskSidebar"><button id="newTask">＋ 새 작업</button><p><b>내 작업 폴더</b></p><small id="workspacePath"></small><input id="workspacePicker" aria-label="작업 폴더" placeholder="이 컴퓨터의 폴더 경로"><button id="setWorkspace" class="secondary">폴더 선택</button><h3>작업</h3><div id="taskList"></div></aside><div id="workArea"><h2 id="taskTitle">어떤 일을 할까요?</h2><nav id="memberNav"><button data-view="drive" class="active">자율주행</button><button data-view="apps">앱</button></nav><div id="taskControls"><span id="taskStateLabel" role="status"></span><button type="button" class="secondary" id="taskStop" hidden>작業を中断</button></div><div id="taskQuestion" aria-live="polite"></div><div id="taskProgress" aria-live="polite"></div>'''
PANELS = '''<section id="appsPanel" hidden><button id="reloadApps" class="secondary">앱 새로고침</button><button id="openMemberFiles" class="secondary">내 파일 · 가져오기 · 내려받기</button><p id="appStatus"></p><iframe id="appFrame" title="내 기기에서 쓰는 앱" sandbox="allow-scripts"></iframe></section><section id="filesPanel" hidden><button id="backToApps" class="secondary">앱으로 돌아가기</button><input id="filePath" value="." aria-label="파일 경로"><div class="fileActions"><button id="browseFiles">폴더 열기</button><button id="readFile">파일 읽기</button><button id="saveFile">저장</button><input id="importFile" type="file" aria-label="파일 가져오기"></div><div id="fileRows"></div><textarea id="fileEditor" aria-label="파일 내용" placeholder="파일을 열거나 새 내용을 쓰세요"></textarea><p id="fileStatus"></p></section></div></div>'''


def workspace_js():
    return 'const MEMBER_FRAME_HTML=' + json.dumps(frame_html(), ensure_ascii=False).replace('</','<\\/') + ';\n' + r'''
let memberView='drive';let currentTask='',taskSignature='',taskListSignature='',taskBusy=false,frameReady=false;let memberApps=[];
function setMemberView(view){memberView=view;for(const b of document.querySelectorAll('#memberNav button'))b.classList.toggle('active',b.dataset.view===(view==='files'?'apps':view));document.getElementById('appsPanel').hidden=view!=='apps';document.getElementById('filesPanel').hidden=view!=='files';document.getElementById('chat').hidden=view!=='drive';document.getElementById('send').hidden=view!=='drive'&&!document.getElementById('taskQuestion').textContent;}
async function memberBoot(){
 if(window.MemberBridge){document.getElementById('workspaceLayout').style.display='block';document.getElementById('importFile').hidden=true}
 document.getElementById('appFrame').srcdoc=MEMBER_FRAME_HTML;
 document.querySelectorAll('#memberNav button').forEach(b=>b.onclick=()=>setMemberView(b.dataset.view));
 document.getElementById('newTask').onclick=()=>{currentTask='';taskSignature='';document.getElementById('taskQuestion').textContent='';document.getElementById('taskStateLabel').textContent='';if(typeof showMemberArtifacts==='function')showMemberArtifacts();document.getElementById('sendButton').disabled=false;document.getElementById('chat').replaceChildren();document.getElementById('taskProgress').replaceChildren();document.getElementById('taskTitle').textContent='새 작업';setMemberView('drive');document.getElementById('message').focus()};
 document.getElementById('setWorkspace').onclick=async()=>{const r=await memberRequest('workspace',{path:document.getElementById('workspacePicker').value});if(!r.success)return alert(r.message||r.error);document.getElementById('workspacePath').textContent=r.workspace;document.getElementById('newTask').click();refreshApps()};
 try{const r=await memberRequest('workspace');document.getElementById('workspacePath').textContent=r.workspace;document.getElementById('workspacePicker').value=r.workspace||'';if(r.fixed){document.getElementById('workspacePicker').disabled=true;document.getElementById('setWorkspace').hidden=true}}catch(e){}
 memberRequest('profile',{}).then(r=>document.getElementById('status').textContent=r.success?'연결됨 · 요청을 처리하고 결과를 이 기기로 받습니다':r.error).catch(()=>document.getElementById('status').textContent='오프라인 · 작업 기록은 이 컴퓨터에 보존됩니다');
 document.getElementById('reloadApps').onclick=refreshApps;document.getElementById('openMemberFiles').onclick=()=>{setMemberView('files');memberFiles('list')};document.getElementById('backToApps').onclick=()=>setMemberView('apps');refreshApps();
 document.getElementById('send').onsubmit=async e=>{e.preventDefault();const input=document.getElementById('message'),text=input.value.trim();if(!text)return;try{const r=await memberRequest('task/start',{task_id:currentTask,message:text});if(!r.success)throw Error(r.message||r.error);currentTask=r.task_id;taskSignature='';input.value='';await refreshTasks()}catch(e){memberBubble('assistant',e.message)}};
 document.getElementById('cancel').hidden=true;document.getElementById('taskStop').onclick=()=>{memberAppGeneration++;return memberRequest('close',{})};
 document.getElementById('export').onclick=async()=>{const r=await memberRequest('export',{});memberBubble('assistant',r.success?'내보내기 완료: '+r.path:r.error)};
 document.getElementById('browseFiles').onclick=()=>memberFiles('list');document.getElementById('readFile').onclick=()=>memberFiles('read');document.getElementById('saveFile').onclick=()=>memberFiles('write');
 document.getElementById('importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;const r=await fetch('/member/upload?name='+encodeURIComponent(file.name)+'&task_id='+encodeURIComponent(currentTask),{method:'POST',headers:{'X-Member-Token':memberToken},body:file});const d=await r.json();document.getElementById('fileStatus').textContent=d.path||d.error;};
 setInterval(memberApprovals,1000);if(!window.MemberBridge)setInterval(memberMedia,500);setInterval(refreshTasks,1000);setInterval(refreshMemberResults,5000);refreshMemberResults();refreshTasks();
}
async function refreshApps(){try{const r=await memberRequest('apps',{task_id:currentTask});memberApps=r.instruments||[];document.getElementById('appStatus').textContent=r.local_error||r.error||(!memberApps.length?'현재 이 기기에서 사용할 수 있는 앱이 없습니다.':'');if(frameReady)sendApps()}catch(e){document.getElementById('appStatus').textContent=e.message}}
function sendApps(){document.getElementById('appFrame').contentWindow.postMessage({memberFrame:'apps',instruments:memberApps},'*')}
let memberAppGeneration=0;let memberAppQueue=Promise.resolve();const memberAppTasks=new Map();
window.addEventListener('message',e=>{
 const frame=document.getElementById('appFrame');if(!frame||e.source!==frame.contentWindow)return;
 const m=e.data||{};if(m.memberFrame==='ready'){frameReady=true;sendApps();return}
 if(m.memberFrame==='import'){
  (async()=>{try{if(typeof memberBrowser==='undefined'||!memberBrowser)throw Error('내 파일에서 가져오세요');const result=await memberBrowser.files.import(m.file);frame.contentWindow.postMessage({memberFrame:'result',id:m.id,result},'*')}catch(error){frame.contentWindow.postMessage({memberFrame:'result',id:m.id,error:error.message},'*')}})();return;
 }
 if(!['execute','request'].includes(m.memberFrame))return;
 const writing=m.memberFrame==='request';
 if(writing?(typeof m.action_id!=='string'||!m.args||typeof m.args!=='object'):(typeof m.code!=='string'||m.code.length>64000))return;
 if(!writing&&typeof memberBrowser!=='undefined'&&memberBrowser){frame.contentWindow.postMessage({memberFrame:'result',id:m.id,error:'앱을 새로고침한 뒤 다시 실행하세요'},'*');return}
 const generation=memberAppGeneration;
 memberAppQueue=memberAppQueue.then(async()=>{try{
  if(generation!==memberAppGeneration)throw Error('작업을 중단했습니다');
  const app=m.app_id||m.action_id?.split(':')[0];
  const r=await memberRequest('task/start',writing?{task_id:memberAppTasks.get(app)||'',message:'',action_id:m.action_id,args:m.args,title:m.title,app_id:app}:{task_id:currentTask,message:'앱 실행',code:m.code});
  if(!r.success)throw Error(r.message||r.error);
  if(app)memberAppTasks.set(app,r.task_id);currentTask=r.task_id;taskSignature='';await refreshTasks();
  const result=await waitMemberTask(r.task_id);
  frame.contentWindow.postMessage({memberFrame:'result',id:m.id,result:result.app_result||result,error:result.success===false?result.error:null},'*');
  if(typeof showMemberArtifacts==='function')showMemberArtifacts(result);await refreshTasks();
 }catch(error){frame.contentWindow.postMessage({memberFrame:'result',id:m.id,error:error.message},'*')}});
});
async function waitMemberTask(id){for(;;){const t=await memberRequest('task?id='+encodeURIComponent(id));if(t.state!=='running')return t.result||{success:false,error:t.state};await new Promise(r=>setTimeout(r,600))}}
async function refreshTasks(){if(taskBusy)return;taskBusy=true;try{const tasks=await memberRequest('tasks');document.getElementById('taskStop').hidden=!(tasks||[]).some(t=>t.state==='running');const list=document.getElementById('taskList');const listSignature=JSON.stringify([tasks,currentTask]);if(listSignature!==taskListSignature){taskListSignature=listSignature;list.replaceChildren();for(const t of tasks||[]){const b=document.createElement('button');b.className=t.id===currentTask?'active':'';b.textContent=t.title+' · '+({running:'진행 중',input_required:'답변 대기',completed:'완료',failed:'확인 필요',unknown:'결과 확인 필요',cancelled:'중단됨'}[t.state]||t.state);b.onclick=()=>{currentTask=t.id;taskSignature='';setMemberView('drive');refreshApps();refreshTasks()};list.append(b)}}if(!currentTask)return;const t=await memberRequest('task?id='+encodeURIComponent(currentTask));const signature=JSON.stringify(t);if(signature===taskSignature)return;taskSignature=signature;document.getElementById('taskTitle').textContent=t.title;if(typeof showMemberArtifacts==='function')showMemberArtifacts(t.result);document.getElementById('workspacePath').textContent=t.workspace;document.getElementById('sendButton').disabled=t.state==='running';document.getElementById('taskStateLabel').textContent=({running:'처리 중 · 이 화면을 열어 두세요',input_required:'답변을 기다리고 있습니다',completed:'완료',failed:'작업을 완료하지 못했습니다',cancelled:'중단됨 · 이미 저장한 파일은 유지됩니다',unknown:'연결이 끊겼습니다 · 저장된 결과를 확인하세요'}[t.state]||'');document.getElementById('taskQuestion').textContent=t.state==='input_required'?(t.result?.input_required||'추가 내용을 알려주세요'):'';document.getElementById('send').hidden=memberView!=='drive'&&t.state!=='input_required';const chat=document.getElementById('chat');chat.replaceChildren();const progress=document.getElementById('taskProgress');progress.replaceChildren();for(const event of t.events||[]){if(event.kind==='user'||event.kind==='assistant'){if(event.kind==='user')progress.replaceChildren();if(event.value)memberBubble(event.kind,event.value)}else if(event.kind==='progress'){const p=document.createElement('div');const v=event.value||{};p.textContent=memberProgressText(v);if(p.textContent&&progress.lastChild?.textContent!==p.textContent)progress.append(p);while(progress.childElementCount>3)progress.firstChild.remove()}}if(t.state!=='running')progress.replaceChildren()}catch(e){}finally{taskBusy=false}}
function memberProgressText(v){const e=v.detail||v;const label={accepted:'요청을 받았습니다',result_ready:'결과를 이 기기로 보내고 있습니다',delivered:'이 기기에 저장했습니다',input_required:'추가 답변이 필요합니다',client_action_required:'이 기기에서 처리하고 있습니다',tool_start:'요청에 필요한 자료와 도구를 확인하고 있습니다',tool_result:'처리 결과를 확인하고 있습니다',thinking:'답변을 준비하고 있습니다',error:'작업을 완료하지 못했습니다'};return label[v.type]||label[e.type]||''}
async function memberFiles(op){try{const r=await memberRequest('file',{op,path:document.getElementById('filePath').value,task_id:currentTask,content:document.getElementById('fileEditor').value});if(r.error)throw Error(r.message||r.error);if(op==='read')document.getElementById('fileEditor').value=r.content||'';if(op==='list'){const rows=document.getElementById('fileRows');rows.replaceChildren();for(const f of r.files||r.items||[]){const b=document.createElement('button');b.textContent=f.name;b.onclick=()=>{document.getElementById('filePath').value=f.path||f.name;memberFiles((f.dir||f.is_dir||['directory','dir'].includes(f.type))?'list':'read')};rows.append(b)}}document.getElementById('fileStatus').textContent=op==='write'?'내 컴퓨터에 저장했습니다':r.path||''}catch(e){document.getElementById('fileStatus').textContent=e.message}}
'''
