"""회원 작업 공간: 로컬 작업 목록·자율주행·공통 앱 프레임·파일 편집."""
import json
from member_app_frame import frame_html

WORKSPACE_STYLE = '''
[hidden]{display:none!important}main{max-width:1280px;padding:22px}header h1{margin:0}#workspaceLayout{display:grid;grid-template-columns:230px minmax(0,1fr);gap:28px;margin-top:24px}#taskSidebar{border-right:1px solid #d4ded7;padding-right:20px}#taskList button{display:block;background:transparent;color:#355548;text-align:left;width:100%;margin:6px 0;padding:12px}#taskList button.active{background:#e2eee7}#workspacePath{display:block;overflow-wrap:anywhere;margin:14px 0;font-size:13px}#memberNav{display:flex;gap:8px;margin:18px 0}#memberNav button{background:#e2e8e2;color:#284f3e}#memberNav button.active{background:#245644;color:white}#appFrame{width:100%;height:70vh;border:0}#taskProgress{color:#5b7266;font-size:13px;max-height:180px;overflow:auto}#fileEditor{width:100%;min-height:300px;font:14px ui-monospace,monospace}#fileRows button{margin:5px;background:#e7eee8;color:#264b37}#filePath{width:70%;padding:12px;border:1px solid #b9c9c0;border-radius:8px}#workspacePicker{width:100%;padding:10px;box-sizing:border-box}#chat{min-height:35vh}#approvals{position:sticky;top:0;z-index:10}#taskTitle{font-size:22px}.taskState{font-size:12px;color:#617366}.fileActions{display:flex;gap:10px;margin:12px 0}@media(max-width:700px){#workspaceLayout{grid-template-columns:1fr}#taskSidebar{border-right:0;border-bottom:1px solid #d4ded7;padding-bottom:15px}#taskList{display:flex;overflow:auto}#taskList button{min-width:150px}header h1{font-size:20px}}
'''
SIDEBAR = '''<div id="workspaceLayout"><aside id="taskSidebar"><button id="newTask">＋ 새 작업</button><p><b>내 작업 폴더</b></p><small id="workspacePath"></small><input id="workspacePicker" aria-label="작업 폴더" placeholder="이 컴퓨터의 폴더 경로"><button id="setWorkspace" class="secondary">폴더 선택</button><h3>작업</h3><div id="taskList"></div></aside><div id="workArea"><h2 id="taskTitle">어떤 일을 할까요?</h2><nav id="memberNav"><button data-view="drive" class="active">자율주행</button><button data-view="apps">앱</button><button data-view="files">내 파일</button></nav><div id="taskProgress" aria-live="polite"></div>'''
PANELS = '''<section id="appsPanel" hidden><button id="reloadApps" class="secondary">앱 새로고침</button><p id="appStatus"></p><iframe id="appFrame" title="허락된 앱" sandbox="allow-scripts"></iframe></section><section id="filesPanel" hidden><input id="filePath" value="." aria-label="파일 경로"><div class="fileActions"><button id="browseFiles">폴더 열기</button><button id="readFile">파일 읽기</button><button id="saveFile">저장</button><input id="importFile" type="file" aria-label="파일 가져오기"></div><div id="fileRows"></div><textarea id="fileEditor" aria-label="파일 내용" placeholder="파일을 열거나 새 내용을 쓰세요"></textarea><p id="fileStatus"></p></section></div></div>'''


def workspace_js():
    return 'const MEMBER_FRAME_HTML=' + json.dumps(frame_html(), ensure_ascii=False).replace('</','<\\/') + ';\n' + r'''
let currentTask='',taskSignature='',taskListSignature='',taskBusy=false,frameReady=false;let memberApps=[];
function setMemberView(view){for(const b of document.querySelectorAll('#memberNav button'))b.classList.toggle('active',b.dataset.view===view);document.getElementById('appsPanel').hidden=view!=='apps';document.getElementById('filesPanel').hidden=view!=='files';document.getElementById('chat').hidden=view!=='drive';document.getElementById('send').hidden=view!=='drive';}
async function memberBoot(){
 if(window.MemberBridge){document.getElementById('workspaceLayout').style.display='block';document.getElementById('importFile').hidden=true}
 document.getElementById('appFrame').srcdoc=MEMBER_FRAME_HTML;
 document.querySelectorAll('#memberNav button').forEach(b=>b.onclick=()=>setMemberView(b.dataset.view));
 document.getElementById('newTask').onclick=()=>{currentTask='';taskSignature='';document.getElementById('sendButton').disabled=false;document.getElementById('chat').replaceChildren();document.getElementById('taskProgress').replaceChildren();document.getElementById('taskTitle').textContent='새 작업';setMemberView('drive');document.getElementById('message').focus()};
 document.getElementById('setWorkspace').onclick=async()=>{const r=await memberRequest('workspace',{path:document.getElementById('workspacePicker').value});if(!r.success)return alert(r.message||r.error);document.getElementById('workspacePath').textContent=r.workspace;document.getElementById('newTask').click();refreshApps()};
 try{const r=await memberRequest('workspace');document.getElementById('workspacePath').textContent=r.workspace;document.getElementById('workspacePicker').value=r.workspace||'';if(r.fixed){document.getElementById('workspacePicker').disabled=true;document.getElementById('setWorkspace').hidden=true}}catch(e){}
 memberRequest('profile',{}).then(r=>document.getElementById('status').textContent=r.success?'연결됨 · 내 컴퓨터에서 작업합니다':r.error).catch(()=>document.getElementById('status').textContent='오프라인 · 작업 기록은 이 컴퓨터에 보존됩니다');
 document.getElementById('reloadApps').onclick=refreshApps;refreshApps();
 document.getElementById('send').onsubmit=async e=>{e.preventDefault();const input=document.getElementById('message'),text=input.value.trim();if(!text)return;try{const r=await memberRequest('task/start',{task_id:currentTask,message:text});if(!r.success)throw Error(r.message||r.error);currentTask=r.task_id;taskSignature='';input.value='';await refreshTasks()}catch(e){memberBubble('assistant',e.message)}};
 document.getElementById('cancel').onclick=()=>memberRequest('close',{});
 document.getElementById('export').onclick=async()=>{const r=await memberRequest('export',{});memberBubble('assistant',r.success?'내보내기 완료: '+r.path:r.error)};
 document.getElementById('browseFiles').onclick=()=>memberFiles('list');document.getElementById('readFile').onclick=()=>memberFiles('read');document.getElementById('saveFile').onclick=()=>memberFiles('write');
 document.getElementById('importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;const r=await fetch('/member/upload?name='+encodeURIComponent(file.name)+'&task_id='+encodeURIComponent(currentTask),{method:'POST',headers:{'X-Member-Token':memberToken},body:file});const d=await r.json();document.getElementById('fileStatus').textContent=d.path||d.error;};
 setInterval(memberApprovals,1000);if(!window.MemberBridge)setInterval(memberMedia,500);setInterval(refreshTasks,1000);setInterval(refreshMemberResults,5000);refreshMemberResults();refreshTasks();
}
async function refreshApps(){try{const r=await memberRequest('apps',{task_id:currentTask});memberApps=r.instruments||[];document.getElementById('appStatus').textContent=r.local_error||r.error||(!memberApps.length?'이 회원에게 열린 앱이 없습니다. 소유자의 회원 공개 설정을 확인하세요':'');if(frameReady)sendApps()}catch(e){document.getElementById('appStatus').textContent=e.message}}
function sendApps(){document.getElementById('appFrame').contentWindow.postMessage({memberFrame:'apps',instruments:memberApps},'*')}
window.addEventListener('message',async e=>{const frame=document.getElementById('appFrame');if(!frame||e.source!==frame.contentWindow)return;const m=e.data||{};if(m.memberFrame==='ready'){frameReady=true;sendApps();return}if(m.memberFrame!=='execute'||typeof m.code!=='string'||m.code.length>64000)return;try{const r=await memberRequest('task/start',{task_id:currentTask,message:'앱 실행',code:m.code});if(!r.success)throw Error(r.message||r.error);currentTask=r.task_id;taskSignature='';const result=await waitMemberTask(r.task_id);frame.contentWindow.postMessage({memberFrame:'result',id:m.id,result:result.app_result||result,error:result.success===false?result.error:null},'*')}catch(error){frame.contentWindow.postMessage({memberFrame:'result',id:m.id,error:error.message},'*')}});
async function waitMemberTask(id){for(;;){const t=await memberRequest('task?id='+encodeURIComponent(id));if(t.state!=='running')return t.result||{success:false,error:t.state};await new Promise(r=>setTimeout(r,600))}}
async function refreshTasks(){if(taskBusy)return;taskBusy=true;try{const tasks=await memberRequest('tasks');const list=document.getElementById('taskList');const listSignature=JSON.stringify([tasks,currentTask]);if(listSignature!==taskListSignature){taskListSignature=listSignature;list.replaceChildren();for(const t of tasks||[]){const b=document.createElement('button');b.className=t.id===currentTask?'active':'';b.textContent=t.title+' · '+({running:'진행 중',completed:'완료',failed:'확인 필요',unknown:'결과 불명'}[t.state]||t.state);b.onclick=()=>{currentTask=t.id;taskSignature='';setMemberView('drive');refreshApps();refreshTasks()};list.append(b)}}if(!currentTask)return;const t=await memberRequest('task?id='+encodeURIComponent(currentTask));const signature=JSON.stringify(t);if(signature===taskSignature)return;taskSignature=signature;document.getElementById('taskTitle').textContent=t.title;document.getElementById('workspacePath').textContent=t.workspace;document.getElementById('sendButton').disabled=t.state==='running';document.getElementById('status').textContent=t.state==='running'?'작업 중 · 화면을 닫아도 연결 프로그램이 계속 실행합니다':t.state==='unknown'?'결과 불명 · 자동 재실행하지 않았습니다':'작업 종료';const chat=document.getElementById('chat');chat.replaceChildren();const progress=document.getElementById('taskProgress');progress.replaceChildren();for(const event of t.events||[]){if(event.kind==='user'||event.kind==='assistant'){if(event.value)memberBubble(event.kind,event.value)}else if(event.kind==='progress'){const p=document.createElement('div');const v=event.value||{};p.textContent=v.content||v.text||v.tool_name||v.name||v.type||'';progress.append(p)}}}catch(e){}finally{taskBusy=false}}
async function memberFiles(op){try{const r=await memberRequest('file',{op,path:document.getElementById('filePath').value,task_id:currentTask,content:document.getElementById('fileEditor').value});if(r.error)throw Error(r.message||r.error);if(op==='read')document.getElementById('fileEditor').value=r.content||'';if(op==='list'){const rows=document.getElementById('fileRows');rows.replaceChildren();for(const f of r.files||r.items||[]){const b=document.createElement('button');b.textContent=f.name;b.onclick=()=>{document.getElementById('filePath').value=f.path||f.name;memberFiles((f.dir||f.is_dir||['directory','dir'].includes(f.type))?'list':'read')};rows.append(b)}}document.getElementById('fileStatus').textContent=op==='write'?'내 컴퓨터에 저장했습니다':r.path||''}catch(e){document.getElementById('fileStatus').textContent=e.message}}
'''
