#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""반환 모양(열 이름) 관측 스윕 — 카탈로그가 "무엇을 돌려주는지"까지 말하게 한다 (2026-08-21).

왜: IBL 조합의 가장 큰 구조적 한계는 *뒷문장을 쓰려면 앞문장의 반환 모양을 봐야 한다*는 것이다.
`>> [table:filter]{where: "연도 == '2024'"}` 가 열 이름을 몰라 실패하면(ep1325) 모델은 한 번
돌려 보고 다시 쓴다 — 최소 2왕복. 카탈로그의 `returns: items` 는 "표다"까지만 말한다.
이 스윕은 부작용 없는 fixture 우주(data/ibl_fixtures.json)를 실행해 실측 열 이름을
`data/ibl_return_shapes.json` 에 적고, ibl_access 가 카탈로그 줄에 ⟨열: …⟩ 로 붙인다.

★변이 축(2026-08-22, F20-1): 색인 키는 `node:action[#op]` 인데 반환 열이 **param 으로**
갈리는 액션이 있다([sense:realty] 의 source=molit/naver/zigbang). 그런 액션은 자기
정의에 `shape_variants: {param=값: '<fixture 코드>'}` 를 선언하고, 여기서 함께 관측해
`node:action@param=값` 키로 적는다 — 카탈로그가 변이별로 열을 말한다.
열 이름은 세계의 명사(입력·외부 API 에 따라 변함)라 src yaml 에 손으로 적지 않고 **관측 데이터**로 둔다.
사용: .venv/bin/python scripts/ibl_shape_sweep.py [--only node:action]   (백엔드 8765 필요)
"""
import json, sys, time, urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
API = "http://127.0.0.1:8765"
OUT = ROOT / "data" / "ibl_return_shapes.json"
MAX_KEYS = 10


def _execute(code, timeout=90):
    req = urllib.request.Request(
        f"{API}/ibl/execute",
        data=json.dumps({"code": code, "project_id": "정보센터", "agent_id": "__self_check__"}).encode(),
        headers={"Content-Type": "application/json"})
    return json.load(urllib.request.urlopen(req, timeout=timeout))


def _final_envelope(resp):
    d = resp.get("result", resp)
    if isinstance(d, str):
        try:
            d = json.loads(d)
        except Exception:
            return None
    if isinstance(d, dict) and "final_result" in d:
        d = d["final_result"]
    if isinstance(d, str):
        try:
            d = json.loads(d)
        except Exception:
            return None
    return d if isinstance(d, dict) else None


def _shape(env):
    """실측 모양 → (kind, keys). items=첫 dict 행들의 키 합집합(등장 순), table=columns."""
    if not isinstance(env, dict):
        return None, []
    items = env.get("items")
    if isinstance(items, list):
        keys = []
        for it in items[:5]:
            if isinstance(it, dict):
                for k in it.keys():
                    if k not in keys and not str(k).startswith("_"):
                        keys.append(str(k))
        return "items", keys[:MAX_KEYS]
    t = env.get("table")
    if isinstance(t, dict) and isinstance(t.get("columns"), list):
        return "table", [str(c) for c in t["columns"]][:MAX_KEYS]
    if isinstance(env.get("columns"), list) and isinstance(env.get("rows"), list):
        return "table", [str(c) for c in env["columns"]][:MAX_KEYS]
    return None, []


def main():
    only = None
    if "--only" in sys.argv:
        only = sys.argv[sys.argv.index("--only") + 1]
    fx = json.load(open(ROOT / "data" / "ibl_fixtures.json", encoding="utf-8"))
    # ★F20-1 (2026-08-22): 변이 축 합류 — 반환 열이 op 이 아니라 param 으로 갈리는
    # 액션(`shape_variants:` 선언)의 변이도 관측한다. 키 = `node:action@param=값`.
    # 건강검진·통화 스윕은 `fixtures` 만 읽으므로 그 측정 우주는 그대로다.
    fixtures = {**fx["fixtures"], **(fx.get("shape_variants") or {})}
    prev = {}
    if OUT.exists():
        try:
            prev = json.load(open(OUT, encoding="utf-8")).get("shapes", {})
        except Exception:
            prev = {}
    shapes = dict(prev)
    ok = fail = skip = 0
    for key, code in sorted(fixtures.items()):
        if only and not key.startswith(only):
            continue
        try:
            env = _final_envelope(_execute(code))
        except Exception as e:
            fail += 1
            print(f"  ✗ {key}: 전송 실패 {e}")
            continue
        if env is None or env.get("success") is False:
            fail += 1
            print(f"  ✗ {key}: {str((env or {}).get('error'))[:80]}")
            continue
        kind, keys = _shape(env)
        if not kind or not keys:
            skip += 1
            continue
        shapes[key] = {"kind": kind, "keys": keys, "observed": time.strftime("%Y-%m-%d")}
        ok += 1
        print(f"  ✓ {key}: {kind} {keys}")
    OUT.write_text(json.dumps({
        "_comment": "GENERATED by scripts/ibl_shape_sweep.py — fixture 실측 반환 열. 직접 수정 금지. "
                    "ibl_access 가 카탈로그 줄에 ⟨열: …⟩ 로 붙인다. 열 이름은 관측 데이터(세계의 명사).",
        "updated": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "shapes": shapes,
    }, ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"\n관측 {ok} · 통화 아님 {skip} · 실패 {fail} → {OUT} (총 {len(shapes)})")


if __name__ == "__main__":
    main()
