"""build_ibl_nodes 파생·병합 계층 (2026-07-18 모듈화 — 1500줄 규칙).

build_ibl_nodes.py 에서 verbatim 이동: tool.json 인덱스/파생, 패키지 어휘 fragment
수집·병합, 폰 매니페스트·fixture·패키지 메타 파생, 최종 직렬화.
"""
from __future__ import annotations
import json
import re
import sys
from pathlib import Path

from iblbuild_common import (
    PACKAGE_DIRS,
    NOT_INSTALLED_PACKAGE_DIRS,
    DEFAULT_RUNS_ON,
    PHONE_VERIFIED_PACKAGES,
)


def build_tool_index(root: Path) -> dict[str, tuple[Path, dict]]:
    """모든 패키지 tool.json 을 스캔해 {tool_name: (pkg_dir, tool_def)} 사전 구축.

    이관 패키지(ibl_actions.yaml 에 tool_json 블록 보유)는 디스크의 tool.json
    (파생 산출물) 대신 *파생 결과*를 읽는다 — 그래야 검증이 소스 수준에서 돌아,
    산출물이 오염돼도 검증은 무결한 소스를 보고(통과), 오염 자체는 --check 의
    바이트 비교가 잡고, 일반 빌드가 재생성으로 치유한다. (산출물을 소스처럼
    검증하면 오염이 빌드를 막아 치유가 불가능해지는 부트스트랩 교착이 생긴다.)
    """
    derived: dict = {}
    try:
        import yaml as _yaml_for_idx
        derived, _ = derive_tool_json_docs(root, _yaml_for_idx)
    except ImportError:
        pass
    index: dict[str, tuple[Path, dict]] = {}
    for rel in PACKAGE_DIRS:
        base = root / rel
        if not base.is_dir():
            continue
        for pkg_dir in sorted(base.iterdir()):
            if not pkg_dir.is_dir():
                continue
            tool_json = pkg_dir / "tool.json"
            if tool_json in derived:
                data = json.loads(derived[tool_json])
            elif not tool_json.is_file():
                continue
            else:
                try:
                    data = json.loads(tool_json.read_text(encoding="utf-8"))
                except json.JSONDecodeError as e:
                    print(
                        f"[build_ibl_nodes] tool.json 파싱 실패 ({pkg_dir.name}): {e}",
                        file=sys.stderr,
                    )
                    continue
            for tool in data.get("tools", []) or []:
                name = tool.get("name")
                if name:
                    if name in index:
                        # 충돌 — 다른 패키지에서 같은 이름 재등록.
                        prev_pkg = index[name][0].name
                        print(
                            f"[build_ibl_nodes] WARN tool 이름 충돌: {name} "
                            f"({prev_pkg} vs {pkg_dir.name})",
                            file=sys.stderr,
                        )
                    index[name] = (pkg_dir, tool)
    return index


# === runs_on 검증 + 폰 매니페스트 파생 (2026-06-11, #3) ===

def derive_phone_manifest(data: dict, root: Path) -> dict:
    """runs_on + 검증된 폰 패키지 → 폰 프로파일 매니페스트.

    runnable_actions(폰서 실행 가능):
      - runs_on == phone_only  → 폰 전용 하드웨어 액션(항상 포함)
      - runs_on == mac_only   → 제외
      - runs_on == anywhere(기본):
          · handler/driver 라우터(패키지 보유) → 패키지가 PHONE_VERIFIED 일 때만
          · 비-패키지(system/engine 등) → 기본 포함(mac_only 로 명시 태그 안 한 한)
    packages: 폰에 번들할 패키지 = PHONE_VERIFIED (Gradle 이 읽음).
    """
    tool_index = build_tool_index(root)
    runnable: list[str] = []
    nodes = data.get("nodes", {}) if isinstance(data, dict) else {}
    for node_name, node in nodes.items():
        if not isinstance(node, dict):
            continue
        for action_name, action in (node.get("actions") or {}).items():
            if not isinstance(action, dict):
                continue
            qualified = f"{node_name}:{action_name}"
            ro = action.get("runs_on", DEFAULT_RUNS_ON)
            if ro == "mac_only":
                continue
            if ro == "phone_only":
                runnable.append(qualified)
                continue
            # anywhere
            tool = action.get("tool")
            pkg = None
            if tool and tool in tool_index:
                pkg = tool_index[tool][0].name
            if pkg is None:
                runnable.append(qualified)          # 비-패키지 액션: 기본 폰가능
            elif pkg in PHONE_VERIFIED_PACKAGES:
                runnable.append(qualified)          # 검증된 폰 패키지
            # else: 미검증 패키지 → 폰서 제외
    return {
        "_comment": "GENERATED by build_ibl_nodes.py — 폰 프로파일(어디서 도는가) 단일 진실 소스. 직접 수정 금지.",
        "packages": sorted(PHONE_VERIFIED_PACKAGES),
        "runnable_actions": sorted(runnable),
    }


def derive_fixtures(data: dict) -> dict:
    """병합된 data 에서 액션별 fixture/exempt 필드를 모아 ibl_fixtures.json 을 파생.

    fixture 는 이제 각 액션 정의(패키지 ibl_actions.yaml / 코어 ibl_nodes_src)에
    `fixture:`(올바른 파라미터 예 하나)·`exempt:`(실행 인자 의존 — 사유) 필드로 산다
    — returns/ops/tool 같은 다른 액션 메타와 동형. *설치된* 어휘에서만 파생되므로
    패키지 제거 → 재빌드 하면 그 fixture 도 함께 빠진다(고아 fixture 문제가 구조적으로
    소멸 — 별도 orphan 검사 불필요). ibl_health_check.py 가 이 파생물을 읽어 통화를 단언한다.
    """
    fixtures: dict = {}
    exempt: dict = {}
    nodes = data.get("nodes", {}) if isinstance(data, dict) else {}
    for node_name, node in nodes.items():
        if not isinstance(node, dict):
            continue
        for action_name, action in (node.get("actions", {}) or {}).items():
            if not isinstance(action, dict):
                continue
            qual = f"{node_name}:{action_name}"
            if action.get("fixture"):
                fixtures[qual] = action["fixture"]
            elif action.get("exempt"):
                exempt[qual] = action["exempt"]
    return {
        "_comment": (
            "GENERATED by build_ibl_nodes.py — 각 액션의 fixture:/exempt: 필드에서 파생. "
            "직접 수정 금지(소스=패키지 ibl_actions.yaml / 코어 ibl_nodes_src). "
            "ibl_health_check.py 가 읽는다."
        ),
        "fixtures": dict(sorted(fixtures.items())),
        "exempt": dict(sorted(exempt.items())),
    }


# === 능력 자기완결화 (Phase 0): 설치된 패키지의 어휘 fragment 병합 ===
# 각 패키지가 자기 폴더에 `ibl_actions.yaml`({node, actions})을 두면 빌드가 흡수한다.
# 설치된 fragment 가 하나도 없으면 출력은 기존 텍스트와 바이트 동일(안전 착지).
# 형식 템플릿: data/packages/not_installed/tools/house-designer/ibl_actions.yaml

def collect_package_fragments(root: Path, yaml_mod) -> tuple[list, list]:
    """설치된 패키지들의 ibl_actions.yaml 수집.

    반환: (fragments, issues)
      fragments = [(pkg_name, node, actions_dict), ...]
      issues    = 형식 오류 메시지 리스트
    """
    fragments: list = []
    issues: list = []
    for rel in PACKAGE_DIRS:
        base = root / rel
        if not base.is_dir():
            continue
        for pkg_dir in sorted(base.iterdir()):
            frag = pkg_dir / "ibl_actions.yaml"
            if not frag.is_file():
                continue
            try:
                doc = yaml_mod.safe_load(frag.read_text(encoding="utf-8"))
            except Exception as e:  # noqa: BLE001
                issues.append(f"{pkg_dir.name}/ibl_actions.yaml 파싱 실패: {e}")
                continue
            if not isinstance(doc, dict):
                issues.append(f"{pkg_dir.name}/ibl_actions.yaml: 최상위가 매핑이 아님")
                continue
            # 형식 A(단일 노드): {node: <name>, actions: {...}}
            # 형식 B(다중 노드): {nodes: {<node>: {actions: {...}}, ...}}  ← radio 등 노드 걸침
            if isinstance(doc.get("nodes"), dict):
                any_ok = False
                for node, ndef in doc["nodes"].items():
                    actions = ndef.get("actions") if isinstance(ndef, dict) else None
                    if not isinstance(actions, dict):
                        issues.append(
                            f"{pkg_dir.name}/ibl_actions.yaml: nodes.{node}.actions 매핑 필요"
                        )
                        continue
                    fragments.append((pkg_dir.name, node, actions))
                    any_ok = True
                if not any_ok:
                    issues.append(
                        f"{pkg_dir.name}/ibl_actions.yaml: nodes 아래 유효 액션 없음"
                    )
            else:
                node = doc.get("node")
                actions = doc.get("actions")
                if not node or not isinstance(actions, dict):
                    issues.append(
                        f"{pkg_dir.name}/ibl_actions.yaml: 'node'+'actions' 또는 'nodes' 필수"
                    )
                    continue
                fragments.append((pkg_dir.name, node, actions))
    return fragments, issues


_TOOL_JSON_MARKER = (
    "build_ibl_nodes.py가 ibl_actions.yaml의 tool_json 블록에서 파생 — 직접 편집 금지. "
    "op-bearing 도구의 op enum/default는 actions의 ops가 단일 소스."
)


def derive_tool_json_docs(root: Path, yaml_mod) -> tuple[dict, list[str]]:
    """설치 패키지들의 tool.json을 ibl_actions.yaml `tool_json:` 블록에서 파생.

    정합성을 검증에서 구조로: 예전에는 src.ops ↔ tool.json op enum/default 를
    삼각검증이 *비교*했다(어긋날 수 있으니). 이제 op-bearing 도구의 enum/default 는
    tool.json 에 저장되지 않고 이 함수가 액션의 ops 블록에서 *주입*한다 —
    어긋남이 존재할 수 없다 (fixture: 필드 → ibl_fixtures.json 파생과 같은 수).

    tool_json 블록 형식 (ibl_actions.yaml 최상위):
      tool_json:
        header: {id, name, description, version, ...}   # tool.json 최상위(tools 외) 통째
        tools:  [{name, description, input_schema, ...}, ...]
                # 액션이 소유(action.tool == name)하고 그 액션에 ops 가 있으면
                # input_schema.properties.op 의 enum/default 는 여기 없어야 한다(빌드가 주입).
                # 액션 미소유 도구(내부 배관 — world_pulse_collectors/web_collector/system_tools
                # 가 이름으로 직접 디스패치)는 원문 그대로 보존된다.

    반환: ({pkg_tool_json_path: canonical_text}, issues)
    블록이 없는 패키지(예: ibl-core, 미이관)는 건너뛴다(손수 유지 유지).
    """
    import copy as _copy

    docs: dict = {}
    issues: list[str] = []
    for rel in PACKAGE_DIRS:
        base = root / rel
        if not base.is_dir():
            continue
        for pkg_dir in sorted(base.iterdir()):
            frag = pkg_dir / "ibl_actions.yaml"
            if not frag.is_file():
                continue
            try:
                doc = yaml_mod.safe_load(frag.read_text(encoding="utf-8"))
            except Exception:  # noqa: BLE001
                continue  # 파싱 오류는 collect_package_fragments 가 이미 보고
            if not isinstance(doc, dict) or not isinstance(doc.get("tool_json"), dict):
                continue

            tj = doc["tool_json"]
            header = tj.get("header")
            tools_src = tj.get("tools")
            if not isinstance(header, dict) or not isinstance(tools_src, list):
                issues.append(f"{pkg_dir.name}: tool_json 블록에 header(dict)+tools(list) 필수")
                continue

            # 액션 소유 맵: tool_name → ops 블록 (형식 A/B 모두)
            owned_ops: dict = {}
            node_defs = (
                doc["nodes"].items() if isinstance(doc.get("nodes"), dict)
                else [(doc.get("node"), {"actions": doc.get("actions") or {}})]
            )
            for _node, ndef in node_defs:
                for aname, acfg in ((ndef or {}).get("actions") or {}).items():
                    if isinstance(acfg, dict) and acfg.get("tool"):
                        owned_ops[acfg["tool"]] = acfg.get("ops")

            out_tools = []
            for entry in tools_src:
                entry = _copy.deepcopy(entry)
                name = entry.get("name")
                if not name:
                    issues.append(f"{pkg_dir.name}: tools 항목에 name 없음")
                    continue
                ops = owned_ops.get(name)
                op_prop = (
                    entry.get("input_schema", {}).get("properties", {}).get("op")
                    if isinstance(entry.get("input_schema"), dict) else None
                )
                if isinstance(ops, dict) and ops.get("values"):
                    if not isinstance(op_prop, dict):
                        issues.append(
                            f"{pkg_dir.name}/{name}: 소유 액션에 ops 가 있는데 "
                            f"input_schema.properties.op 자리가 없음"
                        )
                        continue
                    if "enum" in op_prop or "default" in op_prop:
                        issues.append(
                            f"{pkg_dir.name}/{name}: tool_json 블록에 op enum/default 가 "
                            f"저장돼 있음 — 단일 소스 위반 (actions 의 ops 만 유지하고 지울 것)"
                        )
                        continue
                    op_prop["enum"] = list(ops["values"].keys())
                    if ops.get("default") is not None:
                        op_prop["default"] = ops["default"]
                out_tools.append(entry)

            merged = {"_generated": _TOOL_JSON_MARKER}
            merged.update(header)
            merged["tools"] = out_tools
            docs[pkg_dir / "tool.json"] = (
                json.dumps(merged, ensure_ascii=False, indent=2) + "\n"
            )
    return docs, issues


def collect_dormant_package_qualifiers(root: Path, yaml_mod) -> set[str]:
    """not_installed 패키지들의 ibl_actions.yaml에서 소유 액션 qualifier(node:action) 집합.

    부재-패키지 관용(Phase 4): "철거됐을 뿐 정의는 실존하는" 액션과 "정의 자체가
    사라진 진짜 좀비"를 구분하는 판별 집합. best-effort — 형식 오류는 조용히 건너뛴다
    (dormant 패키지의 fragment 오류는 --check 실패 사유가 아니다, 재설치 시 그때 걸린다).
    """
    quals: set[str] = set()
    for rel in NOT_INSTALLED_PACKAGE_DIRS:
        base = root / rel
        if not base.is_dir():
            continue
        for pkg_dir in sorted(base.iterdir()):
            frag = pkg_dir / "ibl_actions.yaml"
            if not frag.is_file():
                continue
            try:
                doc = yaml_mod.safe_load(frag.read_text(encoding="utf-8"))
            except Exception:  # noqa: BLE001
                continue
            if not isinstance(doc, dict):
                continue
            if isinstance(doc.get("nodes"), dict):
                for node, ndef in doc["nodes"].items():
                    actions = ndef.get("actions") if isinstance(ndef, dict) else None
                    if isinstance(actions, dict):
                        quals.update(f"{node}:{a}" for a in actions)
            else:
                node = doc.get("node")
                actions = doc.get("actions")
                if node and isinstance(actions, dict):
                    quals.update(f"{node}:{a}" for a in actions)
    return quals


# === 능력 메타 자동 도출 (Phase 4, 2026-07-01) ===
# 패키지별 needs_key/weight/locale을 손수 유지하는 어노테이션이 아니라 코드에서 직접
# 스캔해 도출한다 — 단일 진실 소스는 항상 코드(핸들러 자신)이지 사람이 손으로 미러링한
# 메타데이터가 아니다(드리프트 방지, docs/CAPABILITY_SELF_CONTAINMENT_PLAN.md Phase 4).
_KEY_ENV_SUFFIX_RE = re.compile(
    r"^[A-Z][A-Z0-9_]*_(?:API_KEY|API_TOKEN|TOKEN|API_SECRET|SECRET|CLIENT_ID|CLIENT_SECRET|ACCOUNT_ID)$"
)
_DIRECT_ENV_CALL_RE = re.compile(
    r'(?:os\.environ\.get|os\.getenv|get_api_key)\(\s*["\']([A-Z0-9_]+)["\']'
)
_CHECK_API_KEY_RE = re.compile(r'check_api_key\(\s*["\']([a-z0-9_]+)["\']')

# 시스템/런타임 경로 변수 — API 키가 아니므로 needs_key에서 제외.
_META_KEY_EXCLUDE_ENV_VARS = {
    "INDIEBIZ_PROFILE", "INDIEBIZ_USERDATA", "INDIEBIZ_NODE_PATH",
    "INDIEBIZ_RUNTIME_PATH", "INDIEBIZ_PYTHON_PATH",
}
# auth_manager._AUTH_REGISTRY 서비스 중 한국 공식/상용 API로 잠긴 것 (locale:kr 판정 근거).
_KR_LOCKED_AUTH_SERVICES = {
    "kakao", "naver", "law", "dart", "kosis", "data_go_kr", "molit",
    "kopis", "data4library", "nanet",
}
# 레지스트리 밖 직접 env var 중 KR 확정분(교통정보 등 한국 전용 공공 API).
_KR_LOCKED_ENV_VARS = {"ITS_API_KEY", "UTIC_API_KEY"}
# 무거운 의존성(브라우저 자동화·CV·GUI 자동화·영상/TTS 처리) — 표준=keyless∧universal∧light
# 프리셋(Phase 5)의 "light" 판정 근거.
_HEAVY_DEP_MARKERS = (
    "playwright", "moviepy", "cv2", "torch", "whisper", "selenium",
    "pyautogui", "edge_tts", "remotion",
)


def _registry_env_vars(auth_config: dict) -> set[str]:
    """auth_manager._AUTH_REGISTRY 항목 하나에서 env var 이름(들) 추출."""
    t = auth_config.get("type")
    if t in ("header", "query_param"):
        v = auth_config.get("env_var")
        return {v} if v else set()
    if t == "header_pair":
        return set(auth_config.get("headers", {}).values())
    if t == "oauth2":
        return set(auth_config.get("env_vars", {}).values())
    return set()


def _load_auth_registry(root: Path) -> dict:
    """backend/common/auth_manager.py 의 _AUTH_REGISTRY 재사용 — 매핑을 복제하지 않고
    단일 소스를 그대로 import(KR-lock 서비스가 그쪽에서 바뀌면 이쪽도 즉시 정합)."""
    import sys as _sys
    backend_dir = str(root / "backend")
    added = backend_dir not in _sys.path
    if added:
        _sys.path.insert(0, backend_dir)
    try:
        from common.auth_manager import _AUTH_REGISTRY  # type: ignore
        return dict(_AUTH_REGISTRY)
    except Exception:  # noqa: BLE001
        return {}
    finally:
        if added:
            _sys.path.remove(backend_dir)


def derive_package_meta(root: Path, package_dirs=None) -> dict:
    """설치된 각 패키지의 needs_key/weight/locale을 .py 코드 스캔으로 자동 도출 +
    action_owner(어느 액션이 어느 패키지 소유인지)까지 함께 산출 — 런타임(ibl_access.py)이
    "이 액션은 needs_key가 있는데 env var가 없다"를 판정하려면 qualifier→패키지 역참조가
    필요한데, 그 원천은 collect_package_fragments가 이미 갖고 있어 재사용한다(중복 스캔 방지 X,
    fragment 자체는 작아서 재파싱 비용은 무시 가능 — 대신 단일 진실 소스 유지가 이득).

    package_dirs: 스캔할 패키지 루트 목록(root 상대). None이면 PACKAGE_DIRS(installed).
      apply_edition.py 가 not_installed 팩의 메타까지 필요할 때 확장 목록을 넘긴다.
      action_owner 는 항상 installed 기준(collect_package_fragments)이라 이 인자와 무관.

    반환: {
      "packages": {pkg_name: {needs_key: [env_var,...], weight: light|heavy, locale: kr|universal}},
      "action_owner": {"node:action": pkg_name, ...},
    } (양쪽 다 알파벳순 정렬, 결정적).
    """
    registry = _load_auth_registry(root)
    # KR-locked env var 전체 집합 = 직접 확정분 ∪ KR 서비스가 요구하는 env var들.
    kr_env_vars = set(_KR_LOCKED_ENV_VARS)
    for svc in _KR_LOCKED_AUTH_SERVICES:
        cfg = registry.get(svc)
        if cfg:
            kr_env_vars |= _registry_env_vars(cfg)

    result: dict[str, dict] = {}
    for rel in (package_dirs or PACKAGE_DIRS):
        base = root / rel
        if not base.is_dir():
            continue
        for pkg_dir in sorted(base.iterdir()):
            if not pkg_dir.is_dir():
                continue
            py_files = list(pkg_dir.rglob("*.py"))
            if not py_files:
                continue
            needs_key: set[str] = set()
            kr_hit = False
            heavy = False
            for f in py_files:
                try:
                    text = f.read_text(encoding="utf-8")
                except (OSError, UnicodeDecodeError):
                    continue
                for m in _DIRECT_ENV_CALL_RE.finditer(text):
                    name = m.group(1)
                    if name in _META_KEY_EXCLUDE_ENV_VARS or not _KEY_ENV_SUFFIX_RE.match(name):
                        continue
                    needs_key.add(name)
                    if name in kr_env_vars:
                        kr_hit = True
                for m in _CHECK_API_KEY_RE.finditer(text):
                    svc = m.group(1)
                    cfg = registry.get(svc)
                    if cfg:
                        needs_key.update(_registry_env_vars(cfg))
                        if svc in _KR_LOCKED_AUTH_SERVICES:
                            kr_hit = True
                if any(marker in text for marker in _HEAVY_DEP_MARKERS):
                    heavy = True
            result[pkg_dir.name] = {
                "needs_key": sorted(needs_key),
                "weight": "heavy" if heavy else "light",
                "locale": "kr" if kr_hit else "universal",
            }

    action_owner: dict[str, str] = {}
    try:
        import yaml as _yaml_for_meta
    except ImportError:
        _yaml_for_meta = None
    if _yaml_for_meta is not None:
        fragments, _frag_issues = collect_package_fragments(root, _yaml_for_meta)
        for pkg_name, node, actions in fragments:
            for aname in actions:
                action_owner[f"{node}:{aname}"] = pkg_name

    return {
        "packages": dict(sorted(result.items())),
        "action_owner": dict(sorted(action_owner.items())),
    }


def merge_fragments(data: dict, fragments: list) -> list:
    """fragments 를 data['nodes'][node]['actions'] 에 병합(data 변경). 반환: 충돌/오류 issues."""
    issues: list = []
    nodes = data.get("nodes", {}) if isinstance(data, dict) else {}
    for pkg_name, node, actions in fragments:
        node_def = nodes.get(node)
        if not isinstance(node_def, dict):
            issues.append(f"{pkg_name}: 알 수 없는 노드 '{node}'")
            continue
        # 노드의 모든 액션이 이관되면 중앙 src엔 `actions:`가 빈 값(None)으로 남는다 —
        # setdefault는 기존 키가 None이어도 덮어쓰지 않으므로 명시적으로 정규화한다.
        node_actions = node_def.get("actions")
        if node_actions is None:
            node_actions = {}
            node_def["actions"] = node_actions
        for aname, adef in actions.items():
            if aname in node_actions:
                issues.append(
                    f"{pkg_name}: 어휘 충돌 '{node}:{aname}' — 코어/타 패키지에 이미 존재"
                )
                continue
            node_actions[aname] = adef
    return issues


def serialize_nodes_document(header: str, data: dict, yaml_mod) -> str:
    """병합된 data 를 ibl_nodes.yaml 텍스트로 재직렬화 (fragment 존재 시에만 사용)."""
    body = yaml_mod.safe_dump(
        data,
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
        width=1 << 20,
    )
    return header + body
