#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
IndieBiz OS — factory-reset the runtime *learned/tuning* state (the "full" update).

Context
-------
The installer offers two overwrite modes when re-installing over an existing clone:

  * standard — `git reset --hard` overwrites all *tracked* GitHub code + the
    shipped ("standard") IBL vocabulary. Everything git-*ignores* (your .env,
    profile, conversation DBs, projects/, AND your accumulated learning) is left
    untouched. That is all `git reset` does — this script is NOT run.

  * full — same code+vocabulary overwrite, and THEN this script wipes the small
    set of *learned skill + tuning* artifacts back to shipped defaults, so the
    brain starts fresh. Your identity and keys are still kept.

Why a separate script (not just `git clean`)
---------------------------------------------
The learned artifacts are all git-*ignored*, so neither `git reset --hard` nor a
key-safe `git clean` touches them. Resetting them has to be explicit. We use an
allow-list of exactly-what-to-remove (never a subtractive "delete everything
except…" rule), because misclassifying a personal file as resettable is data
loss. A KEEP-guard double-checks that no target ever overlaps the personal set.

What is reset (learned skill + tuning — all rebuildable)
--------------------------------------------------------
  data/ibl_distilled.json              accumulated distillation (learned recipes)
  data/training/ibl_distilled.json     same, training-side accumulation
  data/training/training_balanced.json balanced training accumulation (if present)
  data/ibl_usage.db (+ -wal/-shm)      hippocampus / execution-memory index
  data/forage_memory.db (+ -wal/-shm)  forager memory (7th memory)
  data/model_gear.json                 model-gear tuning preference
  data/package_meta.json               derived package metadata (regenerated by build)
  data/packages/**/.edition_parked     edition markers (so the full edition is restored)

What is ALWAYS kept (identity + keys + history — even in full)
--------------------------------------------------------------
  .env / .env.*                        API keys, owner identity
  data/*_ai_config.json                per-tier provider/model + apiKey
  data/system_ai_memory.db             system-AI short-term memory
  data/system_ai_role.txt / _memo.txt / system_ai_prompts/
  data/my_profile.txt, device_id.txt   who you are / this device
  data/business.db, multi_chat.db      contacts, chats
  data/calendar_events.json            your calendar
  data/world_pulse.db                  consciousness pulse + episodic history
  data/health/, tokens/, projects/     health records, auth tokens, all projects
  photo/storage scans + *_index.db     personal file-scan caches (rebuildable but
                                        derived from YOUR files, not the AI's skill)

After a full reset the caller should rebuild the derived state that the backend
needs: `python scripts/build_ibl_nodes.py` (vocabulary) and — on a machine with
the heavy deps — rebuild the hippocampus index from the shipped training corpus.
The backend also rebuilds a missing hippocampus DB on boot.

Usage
-----
  python scripts/reset_runtime_state.py --dry-run     # show what would be removed
  python scripts/reset_runtime_state.py --yes         # do it (no prompt)
  python scripts/reset_runtime_state.py               # prompt before removing
"""

import argparse
import fnmatch
import glob
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)  # repo root (scripts/ lives inside it)

# --- Allow-list: exactly the learned/tuning artifacts to remove (repo-relative).
#     Entries may be plain paths or globs. SQLite side-files are handled by also
#     removing "<db>-wal" / "<db>-shm" for any *.db target.
RESET_TARGETS = [
    "data/ibl_distilled.json",
    "data/training/ibl_distilled.json",
    "data/training/training_balanced.json",
    "data/ibl_usage.db",
    "data/forage_memory.db",
    "data/model_gear.json",
    "data/package_meta.json",
    "data/packages/**/.edition_parked",
]

# --- KEEP-guard: personal / identity / key / history paths that must NEVER be
#     removed. Patterns match the repo-relative path (posix-style). This is
#     defense-in-depth: if RESET_TARGETS is ever edited to accidentally include
#     one of these, the reset aborts instead of destroying user data.
KEEP_PATTERNS = [
    ".env", ".env.*",
    "data/*_ai_config.json",
    "data/claude_code_*",
    "data/system_ai_memory.db",
    "data/system_ai_role.txt", "data/system_ai_memo.txt", "data/system_ai_prompts/*",
    "data/my_profile.txt", "data/device_id.txt",
    "data/business.db", "data/multi_chat.db",
    "data/calendar_events.json",
    "data/world_pulse.db",
    "data/switches.json", "data/plan.md",
    "data/health/*", "tokens/*", "projects/*", "backend/data/*",
    "data/browser_cookies/*",
    "*/api_key.json", "*/config.json", "*/config.yaml",
    "*photo_index.db", "*storage_index.db", "*_scans/*",
    "*.db-shm", "*.db-wal",  # never remove side-files on their own; handled per-db below
]


def _relposix(path):
    return os.path.relpath(path, ROOT).replace(os.sep, "/")


def _is_kept(path):
    rel = _relposix(path)
    for pat in KEEP_PATTERNS:
        if fnmatch.fnmatch(rel, pat) or fnmatch.fnmatch(rel, pat.rstrip("/") + "/*"):
            return pat
    return None


def _inside_root(path):
    ap = os.path.abspath(path)
    return ap == ROOT or ap.startswith(ROOT + os.sep)


def _expand(target):
    """Resolve a RESET_TARGETS entry (path or glob) to concrete existing paths,
    adding SQLite -wal/-shm side-files for any *.db path."""
    abs_target = os.path.join(ROOT, target)
    matches = glob.glob(abs_target, recursive=True)
    out = []
    for m in matches:
        out.append(m)
        if m.endswith(".db"):
            for side in (m + "-wal", m + "-shm"):
                if os.path.exists(side):
                    out.append(side)
    return out


def main():
    ap = argparse.ArgumentParser(description="Factory-reset IndieBiz OS learned/tuning state.")
    ap.add_argument("--mode", default="full", choices=["full"],
                    help="Only 'full' has an effect; present for symmetry with the installer.")
    ap.add_argument("--yes", action="store_true", help="Do not prompt before removing.")
    ap.add_argument("--dry-run", action="store_true", help="Show what would be removed and exit.")
    args = ap.parse_args()

    # Collect concrete removals.
    to_remove = []
    for t in RESET_TARGETS:
        to_remove.extend(_expand(t))
    # de-dup, stable order
    seen, ordered = set(), []
    for p in to_remove:
        ap_ = os.path.abspath(p)
        if ap_ not in seen:
            seen.add(ap_)
            ordered.append(ap_)

    # Safety pass: nothing may escape the repo, nothing may hit the KEEP set.
    safe = []
    for p in ordered:
        if not _inside_root(p):
            print("[reset:abort] target escapes repo root: %s" % p, file=sys.stderr)
            sys.exit(2)
        kept = _is_kept(p)
        if kept:
            print("[reset:abort] target %s matches KEEP pattern %r — refusing (bug in RESET_TARGETS)."
                  % (_relposix(p), kept), file=sys.stderr)
            sys.exit(2)
        safe.append(p)

    if not safe:
        print("[reset] nothing to reset — learned/tuning state is already clean.")
        return

    print("[reset] full update: the following learned/tuning artifacts will be reset to shipped defaults")
    print("        (your .env, profile, conversations, projects, and episodic history are kept):")
    for p in safe:
        print("   - " + _relposix(p))

    if args.dry_run:
        print("[reset] dry-run: nothing removed.")
        return

    if not args.yes:
        try:
            ans = input("proceed? [y/N] ").strip().lower()
        except EOFError:
            ans = ""
        if ans not in ("y", "yes"):
            print("[reset] aborted.")
            return

    removed = 0
    for p in safe:
        try:
            if os.path.isdir(p) and not os.path.islink(p):
                shutil.rmtree(p)
            else:
                os.remove(p)
            removed += 1
        except FileNotFoundError:
            pass
        except Exception as e:
            print("[reset:warn] could not remove %s: %s" % (_relposix(p), e), file=sys.stderr)

    print("[reset] done — removed %d artifact(s). Rebuild vocabulary/hippocampus after this "
          "(scripts/build_ibl_nodes.py; the backend rebuilds a missing hippocampus on boot)." % removed)


if __name__ == "__main__":
    main()
